Handle different base OS image caching better

diff --git a/rootfs/bin/rm-serial b/rootfs/bin/rm-serial
--- a/rootfs/bin/rm-serial
+++ b/rootfs/bin/rm-serial
@@ -1,2 +1,6 @@
 #!/bin/sh
+if ! rm-is-running; then
+  echo "Error: rm is not running" >/dev/stderr
+  exit 1
+fi
 exec serial-client /run/rm/serial "$@"
diff --git a/rootfs/bin/rm-start b/rootfs/bin/rm-start
--- a/rootfs/bin/rm-start
+++ b/rootfs/bin/rm-start
@@ -1,10 +1,18 @@
 #!/bin/bash
-mkdir -p /run/rm
+set -e
+
+if rm-is-running; then
+  echo "Error: rm is running" >/dev/stderr
+  exit 1
+fi
 
 args=""
-if qemu-img snapshot -l /data/rootfs.qcow2 | grep -q rm; then
-  args="-loadvm rm"
+paused=false
+if rm-is-paused; then
+  paused=true
+  args="-loadvm running"
 fi
+mkdir -p /run/rm
 
 case "$1" in
 -D | --detached)
@@ -15,7 +23,7 @@ case "$1" in
     -m 2048 \
     -kernel /zImage \
     -dtb /qemu.dtb \
-    -drive if=sd,file=/data/rootfs.qcow2,format=qcow2,index=2 \
+    -drive if=sd,file=/rootfs.qcow2,format=qcow2,index=2 \
     -append "console=ttymxc0 rootfstype=ext4 root=/dev/mmcblk2p2 rw rootwait init=/sbin/init" \
     -nic user,hostfwd=tcp::22-:22,hostfwd=tcp::8888-:8888 \
     -monitor unix:/run/rm/monitor,server=on,wait=off \
@@ -25,6 +33,9 @@ case "$1" in
     -display none \
     -daemonize \
     "$args"
+  if $paused; then
+    rm-monitor commit sd2
+  fi
   if [[ "$2" == "--wait" ]]; then
     echo "Waiting for ssh to start..." >/dev/stderr
     while ! rm-exec true >/dev/null 2>&1; do
@@ -33,6 +44,12 @@ case "$1" in
   fi
   ;;
 "")
+  if $paused; then
+    {
+      sleep 1
+      rm-monitor commit sd2 || true
+    } &
+  fi
   qemu-system-arm \
     -machine mcimx7d-sabre \
     -cpu cortex-a9 \
@@ -40,7 +57,7 @@ case "$1" in
     -m 2048 \
     -kernel /zImage \
     -dtb /qemu.dtb \
-    -drive if=sd,file=/data/rootfs.qcow2,format=qcow2,index=2 \
+    -drive if=sd,file=/rootfs.qcow2,format=qcow2,index=2 \
     -append "console=ttymxc0,115200 rootfstype=ext4 root=/dev/mmcblk2p2 rw rootwait init=/sbin/init" \
     -nic user,hostfwd=tcp::22-:22,hostfwd=tcp::8888-:8888 \
     -monitor unix:/run/rm/monitor,server=on,wait=off \
