Only checksum expected size

diff --git a/emulator/bin/initialize-image-base b/emulator/bin/initialize-image-base
--- a/emulator/bin/initialize-image-base
+++ b/emulator/bin/initialize-image-base
@@ -41,6 +41,7 @@ extracted=$(mktemp -d)/image
 # shellcheck disable=SC2064,SC2086
 trap "rm -rf '$(dirname \"$extracted\")'" EXIT
 codexctl extract --out "$extracted" "$image"
+# truncate -s ">283115008" "$extracted"
 rootfs="$DATADIR/$VERSION.qcow2"
 echo "Creating $VERSION.qcow2..."
 pushd "$DATADIR" >/dev/null
@@ -51,12 +52,29 @@ popd >/dev/null
 rm-busybox-start "$rootfs"
 echo "Initializing $VERSION.qcow2..."
 hash=$(sha256sum "$extracted" | cut -d' ' -f1)
+size=$(stat --printf="%s" "$extracted")
 dd if="$extracted" bs=160000 | gzip -1 | rm-busybox-exec "gunzip -c | dd of=/dev/mmcblk2p2 bs=160000"
 rm-busybox-exec <<EOF
   set -e
-  echo "$hash  /dev/mmcblk2p2" | sha256sum -c
+  hash=\$(head -c $size /dev/mmcblk2p2 | sha256sum | cut -d' ' -f1)
+  if [[ "\$hash" != "$hash" ]];then
+    echo "Error: sha256sum of mmcblk2p2 does not match expected" >/dev/stderr
+    echo "  Expected: $hash" >/dev/stderr
+    echo "  actual: \$hash" >/dev/stderr
+    echo "  size: $size" >/dev/stderr
+    echo "  actual size: \$(stat --printf="%s" /dev/mmcblk2p2)" >/dev/stderr
+    exit 1
+  fi
   dd if=/dev/mmcblk2p2 of=/dev/mmcblk2p3 bs=160000
-  echo "$hash  /dev/mmcblk2p3" | sha256sum -c
+  hash=\$(head -c $size /dev/mmcblk2p3 | sha256sum | cut -d' ' -f1)
+  if [[ "\$hash" != "$hash" ]];then
+    echo "Error: sha256sum of mmcblk2p3 does not match expected" >/dev/stderr
+    echo "  Expected: $hash" >/dev/stderr
+    echo "  actual: \$hash" >/dev/stderr
+    echo "  size: $size" >/dev/stderr
+    echo "  actual size: \$(stat --printf="%s" /dev/mmcblk2p3)" >/dev/stderr
+    exit 1
+  fi
   cd /mnt
   mkdir boot
   mount /dev/mmcblk2p1 boot
