better error handling

diff --git a/emulator/bin/initialize-image-base b/emulator/bin/initialize-image-base
--- a/emulator/bin/initialize-image-base
+++ b/emulator/bin/initialize-image-base
@@ -47,7 +47,7 @@ echo "Creating $VERSION.qcow2..."
 pushd "$DATADIR" >/dev/null
 cp "${ROOTDIR}/artifact/base.qcow2" "$rootfs"
 # shellcheck disable=SC2064,SC2086
-trap "rm -r '$(dirname \"$extracted\")' '${rootfs}'" EXIT
+trap "rm -rf '$(dirname \"$extracted\")' '${rootfs}'" EXIT
 popd >/dev/null
 rm-busybox-start "$rootfs"
 echo "Initializing $VERSION.qcow2..."
@@ -58,31 +58,35 @@ rm-busybox-exec <<EOF
   set -e
   hash=\$(head -c $size /dev/mmcblk2p2 | sha256sum | cut -d' ' -f1)
   if [[ "\$hash" != "$hash" ]];then
-    echo "Error: sha256sum of mmcblk2p2 does not match expected" >/dev/stderr
-    echo "  Expected: $hash" >/dev/stderr
-    echo "  actual: \$hash" >/dev/stderr
-    echo "  size: $size" >/dev/stderr
-    echo "  actual size: \$(stat -c "%s" /dev/mmcblk2p2)" >/dev/stderr
+    echo "Error: sha256sum of mmcblk2p2 does not match expected"
+    echo "  Expected: $hash"
+    echo "  actual: \$hash"
+    echo "  size: $size"
     exit 1
   fi
-  /sbin/fsck.ext4 -p /dev/mmcblk2p2
-  dd if=/dev/mmcblk2p2 of=/dev/mmcblk2p3 bs=160000
+  if ! /sbin/fsck.ext4 -p /dev/mmcblk2p2;then
+    echo "Error: mmcblk2p2 fsck failed"
+    exit 1
+  fi
+  if ! dd if=/dev/mmcblk2p2 of=/dev/mmcblk2p3 bs=160000;then
+    echo "Error: Failed to copy mmcblk2p2 to mmcblk2p3"
+  fi
   hash=\$(head -c $size /dev/mmcblk2p3 | sha256sum | cut -d' ' -f1)
   if [[ "\$hash" != "$hash" ]];then
-    echo "Error: sha256sum of mmcblk2p3 does not match expected" >/dev/stderr
-    echo "  Expected: $hash" >/dev/stderr
-    echo "  actual: \$hash" >/dev/stderr
-    echo "  size: $size" >/dev/stderr
-    echo "  actual size: \$(stat -c "%s" /dev/mmcblk2p3)" >/dev/stderr
+    echo "Error: sha256sum of mmcblk2p3 does not match expected"
+    echo "  Expected: $hash"
+    echo "  actual: \$hash"
+    echo "  size: $size"
     exit 1
   fi
-  /sbin/fsck.ext4 -p /dev/mmcblk2p3
-  cd /mnt
-  mkdir boot
-  /sbin/fsck.vfat -p /dev/mmcblk2p1
-  mount /dev/mmcblk2p1 boot
-  dd if=/dev/zero of=boot/uboot.env count=1024
-  # rm-chroot a mkdir -p /run/lock && /usr/sbin/fw_setenv active_partition 2
+  if ! /sbin/fsck.ext4 -p /dev/mmcblk2p3;then
+    echo "Error: mmcblk2p3 fsck failed"
+    exit 1
+  fi
+  if ! /sbin/fsck.vfat -p /dev/mmcblk2p1;then
+    echo "Error: mmcblk2p1 fsck failed"
+    exit 1
+  fi
 EOF
 rm -rf "$(dirname "$extracted")"
 if $stop; then
