Better busybox handling

diff --git a/emulator/bin/rm-busybox-start b/emulator/bin/rm-busybox-start
--- a/emulator/bin/rm-busybox-start
+++ b/emulator/bin/rm-busybox-start
@@ -13,6 +13,12 @@ if [ ! -f "$image" ]; then
 fi
 STATEDIR=${STATEDIR:-/run/rm}
 mkdir -p "$STATEDIR"
+imagestate="$STATEDIR/busybox-rootfs.qcow2"
+if [ -f "$imagestate" ] && lsof "$(readlink -f "$imagestate")" 2>/dev/null | grep -q qemu-system-arm;then
+  echo "Error: Busybox is currently running" >/dev/stderr
+  exit 1
+fi
+ln -sf "$image" "$imagestate"
 qemu-system-arm \
   -machine \
   virt \
