Try to reduce rm-serial overlap

diff --git a/emulator/bin/rm-busybox-stop b/emulator/bin/rm-busybox-stop
--- a/emulator/bin/rm-busybox-stop
+++ b/emulator/bin/rm-busybox-stop
@@ -32,17 +32,26 @@ if [ ! -S "$serial" ]; then
   exit 1
 fi
 if $verbose; then
-  socat STDIO,ignoreeof UNIX-CONNECT:"$serial" 2>&1 &
+  if [ -f "$serial.log" ]; then
+    tail -f "$serial.log" &
+    # shellcheck disable=SC2064
+    trap "kill -TERM $!" EXIT
+  else
+    echo "Unable to find busybox-serial.log"
+  fi
 fi
 rm-busybox-umount
 # shellcheck disable=SC2016
-echo 'kill -9 "$(pgrep -P 1 sh)" || true' | rm-busybox-exec
-serial-client "$serial" exit
+rm-busybox-exec sh -c 'kill -9 "$(pgrep -P 1 sh)" || true' || true
+serial-client "$serial" exit || true
 echo "Waiting for busybox to stop..."
-if [ -S "$serial" ]; then
-  socat STDIO,ignoreeof UNIX-CONNECT:"$serial" >/dev/null 2>&1 || true
-fi
 while lsof "$image" 2>/dev/null | grep -q qemu-system-arm; do
   sleep 0.1
 done
-rm -f "$STATEDIR/busybox-rootfs.qcow2"
+rm -f "$STATEDIR/busybox-rootfs.qcow2" "$STATEDIR/busybox-serial.log"
+if $verbose; then
+  set +e
+  code="$(trap -p EXIT)"
+  trap - EXIT
+  eval "${code:9:-6}"
+fi
