Rely on more being installed on the system

diff --git a/appimage/entrypoint b/appimage/entrypoint
--- a/appimage/entrypoint
+++ b/appimage/entrypoint
@@ -21,12 +21,38 @@ _tmp_bin=rm-qemu-bin \
 _tmp_lib=rm-qemu-lib \
 _tmp_share=rm-qemu-share \
 quick-sharun \
-  /usr/bin/ssh{,-keygen} \
   /usr/bin/{nc,rm2fb-emu}
 
-sed -i -e 's|_tmp_bin=""|_tmp_bin="rm-qemu-bin"|' "${APPDIR}/bin/path-mapping-hardcoded.src.hook"
-sed -i -e 's|_tmp_lib=""|_tmp_lib="rm-qemu-lib"|' "${APPDIR}/bin/path-mapping-hardcoded.src.hook"
-sed -i -e 's|_tmp_share=""|_tmp_share="rm-qemu-share"|' "${APPDIR}/bin/path-mapping-hardcoded.src.hook"
+_hook="${APPDIR}/bin/path-mapping-hardcoded.src.hook"
+if [ -f "$_hook" ];then
+  sed -i -e 's|_tmp_bin=""|_tmp_bin="rm-qemu-bin"|' "$_hook"
+  sed -i -e 's|_tmp_lib=""|_tmp_lib="rm-qemu-lib"|' "$_hook"
+  sed -i -e 's|_tmp_share=""|_tmp_share="rm-qemu-share"|' "$_hook"
+else
+  cat <<-'EOF' > "$_hook"
+  #!/bin/sh
+  _tmp_bin="rm-qemu-bin"
+  _tmp_lib="rm-qemu-lib"
+  _tmp_share="rm-qemu-share"
+
+  if ! command -v ln 1>/dev/null; then
+      >&2 echo "path-mapping-hardcoded: ERROR we cannot make symlinks"
+      >&2 echo "because command 'ln' is missing from the system! Aborting..."
+      exit 1
+  fi
+
+  if [ -n "$_tmp_bin" ]; then
+      ln -sfn "$APPDIR"/bin /tmp/"$_tmp_bin"
+  fi
+  if [ -n "$_tmp_lib" ]; then
+      ln -sfn "$APPDIR"/lib /tmp/"$_tmp_lib"
+  fi
+  if [ -n "$_tmp_share" ]; then
+      ln -sfn "$APPDIR"/share /tmp/"$_tmp_share"
+  fi
+EOF
+  chmod +x "$_hook"
+fi
 
 # Copy static files
 cp \
diff --git a/rootfs/bin/initialize-image b/rootfs/bin/initialize-image
--- a/rootfs/bin/initialize-image
+++ b/rootfs/bin/initialize-image
@@ -29,7 +29,8 @@ fi
 DATADIR="${DATADIR:-/data}"
 echo "Extracting image..." >/dev/stderr
 extracted=$(mktemp -d)/image
-trap 'rm -r $(dirname $extracted)' EXIT
+# Remove the extracted image when we are done
+trap "rm -r '$(dirname $extracted)'" EXIT
 codexctl extract --out "$extracted" "$image"
 rootfs="$DATADIR/$VERSION.qcow2"
 echo "Creating $VERSION.qcow2..." >/dev/stderr
@@ -41,6 +42,8 @@ qemu-img create \
   --options compression_type=zstd \
   "$rootfs" \
   8G
+# If we fail at this point, we
+trap "rm -r '$(dirname $extracted)' '${ROOTDIR}/base.qcow2'" EXIT
 popd >/dev/null
 echo "Initializing $VERSION.qcow2..." >/dev/stderr
 guestfish --rw --blocksize=512 --add "$rootfs" <<EOF
@@ -48,6 +51,8 @@ run
 upload "$extracted" /dev/sda2
 upload "$extracted" /dev/sda3
 EOF
+rm -r "$(dirname $extracted)"
+trap "rm '${ROOTDIR}/base.qcow2'" EXIT
 for dev in 2 3; do
   echo "Setting up mmcblk2p$dev partition..." >/dev/stderr
   guestfish --rw --blocksize=512 --add "$rootfs" <<EOF
@@ -121,5 +126,6 @@ rm-exec <<EOT
   echo "Setting up mmcblk2p4 partition..." >/dev/stderr
   mkfs.ext4 -E nodiscard /dev/mmcblk2p4
 EOT
+trap - EXIT
 rm-stop --wait
 shrink-image "$rootfs"
diff --git a/rootfs/bin/rm-start b/rootfs/bin/rm-start
--- a/rootfs/bin/rm-start
+++ b/rootfs/bin/rm-start
@@ -51,6 +51,10 @@ case "$1" in
         echo "  Please rm-monitor q && rm-ensure-ssh and then try again." >/dev/stderr
         exit 1
       fi
+      if [[ "$output" == *"Segmentation fault"* ]] || [ $ret -eq 139 ];then
+        echo "Error: ssh executable is broken." >/dev/stderr
+        exit 1
+      fi
       sleep 1
     done
   fi
